<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net8.0;net9.0;net10.0;netstandard2.1;netstandard2.0</TargetFrameworks>
		<PackageReleaseNotes>
			___ Changes  ---
			Fixed arrays are now pinnable and use ref this[...]
			Added FixedPtrArry they are also pinnable, but no ref this[...]
			Added function overloads named *_str which accept byte* instead of string
			--- Changes  ---
			Correct description -&gt; release notes are now in the package release note section
			--- Changes ---
			Added hwcontext for OpenCL, DirectX12, Vulkan and Cuda
			--- BugFix ---
			Last version build for FFmpeg 9.0 (pre)

		</PackageReleaseNotes>
		<Description>
			Based on FFmpeg.AutoGen by Ruslan Balanukhin with minor changes to use with FFmpegDotNet.
			All classes and structs are renamed to start with '_'.
			FFmpeg auto generated unsafe bindings for C#/.NET and Mono.
		</Description>
		<LangVersion>latest</LangVersion>
		<Description>FFmpeg auto generated unsafe bindings for C#/.NET and Mono.</Description>
		<GeneratePackageOnBuild Condition=" $(Configuration) == 'Release' ">true</GeneratePackageOnBuild>
	</PropertyGroup>

	<PropertyGroup>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
		<NoWarn>108;169;618;1573;1591;1701;1702;1705;8981</NoWarn>
		<TreatWarningsAsErrors>false</TreatWarningsAsErrors>
		<WarningsAsErrors />
		<DocumentationFile>bin\$(Configuration)\$(TargetFramework)\$(AssemblyName).xml</DocumentationFile>
	</PropertyGroup>

	<PropertyGroup>
		<!-- Build symbol package (.snupkg) to distribute the PDB containing Source Link -->
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<Title>FFmpeg._AutoGen</Title>
		<Product>FFmpeg._AutoGen</Product>
		<Version>9.0.1.0</Version>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.SourceLink.GitHub" PrivateAssets="all" />
		<PackageReference Include="System.Runtime.CompilerServices.Unsafe" />
	</ItemGroup>

</Project>
