/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n8.1.2-31-g8c9502e9b0-20260729"
#endif /* AVUTIL_FFVERSION_H */
