/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-125708-gccc57378b3-20260721"
#endif /* AVUTIL_FFVERSION_H */
